### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by kyx0r** [mcsimps2/zotacbot#1]
Hi tried your bot, there is error:

Exception in <function login at 0x7f4c6fbb6ee0>: 'NoneType' object has no attribute 'status_code'

after fixing that error i get 

Exception in <function login at 0x7fc5311a6ee0>: HTTPSConnectionPool(host='www.zotacstore.com', port=443): Max retries exceeded with url: /us/customer/account/login/ (Caused by ResponseError('too many 503 error responses'))

Did they chance their login page in those 3 month's?

**Comment by Ribwich** [comment]
I'm receiving the same error:

Attempting to log in as xxxxxxxxxxx@gmail.com
Loading login page
Exception in <function login at 0x00000272EEFFE040>: 'NoneType' object has no attribute 'status_code'

@kyx0r how did you fix the the first error?

**Comment by kyx0r** [comment]
@Ribwich I just removed the line of code that had status_code in it. 
https://github.com/mcsimps2/zotacbot/blob/master/zotacbot/client.py#L44

But what it does now is trigger the exception without actually checking the page status code. But it still does not work.

**Comment by mcsimps2** [comment]
Zotac added anti-bot protection to its website, so this repo is now defunct.
As a demonstration, you can load the following login page in your browser.
```
LOGIN_PAGE = "https://www.zotacstore.com/us/customer/account/login/"
```

However, attempting to do it with the Python `requests` library gives you a 503 service unavailable error.

```
import requests
resp = requests.get(LOGIN_PAGE)
print(resp)
print(resp.status_code)
print(resp.text)
```

From a brief skim, it looks like it's using a JavaScript snippet from CloudFlare to act as a "challenge," which, of course, isn't processed by the requests library.  Thus, CloudFlare detects the bot and responds with a 503.  The challenge identifier is `/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1`.

[Read more here on this repo](https://github.com/scaredos/cfresearch)

My recommendation would be to spin up a bot that uses Selenium or some other Firefox/Chrome driver which you can control programmatically. This will ensure things like JavaScript and CSRF do not become barriers.

I will update the repo README to mark it as defunct.  Thanks for bringing this to my attention.
